spring:
  datasource:
    url: jdbc:h2:mem:demo
    username: h2
    password: h2
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: none