CREATE TABLE ACCOUNT (ID IDENTITY CONSTRAINT ACCOUNT_PK PRIMARY KEY,
                      LOGIN VARCHAR(255) CONSTRAINT ACCOUNT_LOGIN UNIQUE NOT NULL,
                      PASSWORD BLOB CONSTRAINT ACCOUNT_PASSWORD NOT NULL,
                      )
